version: "3.7"

services:
  # Product Core Service + DB
  product_db: # Name and environment variables must match datasource configuration in application.yml
    image: mysql:5.7
    volumes:
      - "./data_products:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 1337babe
      MYSQL_DATABASE: products
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: c0ffeebabe
    expose: # Opens ports locally in the docker compose network
      - "3306"
    networks:
      - webshop-network

  product_service:
    build:
      context: ./webshop-core-product-service
    ports:
      - "9250:8080"
    networks:
      - webshop-network
    depends_on:
      - product_db
    restart: on-failure # Try again if database was not ready

  # Category Core Service + DB
  category_db: # Name and environment variables must match datasource configuration in application.yml
    image: mysql:5.7
    volumes:
      - "./data_category:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: category_db
      MYSQL_USER: categoryuser
      MYSQL_PASSWORD: geheim
    expose:
      - "3306" # Opens ports locally in the docker compose network
    networks:
      - webshop-network

  category_service:
    build:
      context: ./webshop-core-category-service
    ports:
      - "9252:8080"
    networks:
      - webshop-network
    depends_on:
      - category_db
    restart: on-failure # Try again if database was not ready

  # User Core Service + DB
  user_db: # Name and environment variables must match datasource configuration in application.yml
    image: mysql:5.7
    volumes:
      - "./data_users:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: usercore
      MYSQL_PASSWORD: usercore
    expose: # Opens ports locally in the docker compose network
      - "3306"
    networks:
      - webshop-network

  user_service:
    build:
      context: ./webshop-core-user-service
    ports:
      - "9251:8080"
    networks:
      - webshop-network
    depends_on:
      - user_db
    restart: on-failure # Try again if database was not ready

volumes:
  data_products:
  data_users:
  data_category:

networks:
  webshop-network:
    driver: bridge
