server:
  port: 8080
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 10000
  ReadTimeout: 10000

zuul:
  ignoredServices: '*'
  routes:
    user-service: /user-api/**
    inventory-service: /inventory-api/**