spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://category-db:3306/category?serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
    username: categoryuser
    password: geheim