version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - './db_data:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: 1337babe
            MYSQL_DATABASE: productdb
            MYSQL_USER: webshopuser
            MYSQL_PASSWORD: c0ffeebabe
        #ports:
            # <Port exposed> : < MySQL Port running inside container>
        #    - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
        networks:
          - ps-network
        restart: always

    productservice:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - '8888:8080'
        networks:
          - ps-network
        depends_on:
          - db
        restart: on-failure

volumes:
    db_data:

networks:
    ps-network:
        driver: bridge

