server:
  port: 8080
spring:
  application:
    name: inventory-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8080/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
# See:
# https://github.com/spring-cloud/spring-cloud-netflix/issues/2785#issuecomment-374941647
# https://stackoverflow.com/a/50549755
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
