server:
  port: 8080
spring:
  application:
    name: inventory-proxy
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8080/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
