#%RAML 1.0
title: WebShop Products Service
version: v1
baseUri:

uses:
  library: types.raml

/products:
  get:
    description: Retrieve the list of products
    responses:
      200:
        body:
          application/json:
            type: library.Product[]
            example: |
              [
                {
                  "id": 1,
                  "name": "MacBook Air",
                  "price": 1099.0,
                  "details": "A light laptop from Apple.",
                  "category": {
                    "id": 1,
                    "name": "electronics"
                  }
                }
              ]

  post:
  /{productId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: library.Product
              example: |
                {
                  "id": 1,
                  "name": "MacBook Air",
                  "price": 1099.0,
                  "details": "A light laptop from Apple.",
                  "category": {
                    "id": 1,
                    "name": "electronics"
                    }
                }
        204:
    delete:
#      access_token:
#        displayName: Access Token
#        type: string
#        description: Token giving you permission to make call
#        required: true
  /search:
    get:
      queryParameters:
        text:
          displayName: Query Text
          type: string
          description: The text to search the product names and descriptions for
          example: MacBook
          required: false
        price:
          displayName: Product Price
          type: number
          example: 1099.0
          required: false
        category:
          displayName: Product Category
          type: string
          example: electronics
          required: false
      responses:
        200:
          body:
            application/json:
              type: library.Product[]
              example: |
                [
                  {
                    "id": 1,
                    "name": "MacBook Air",
                    "price": 1099.0,
                    "details": "A light laptop from Apple.",
                    "category": {
                      "id": 1,
                      "name": "electronics"
                      }
                  }
                ]
