#%RAML 1.0 Library
types:
  Role:
    type: object
    properties:
      id:
        type: integer
        required: true
      type:
        type: string
        required: true
      level:
        type: integer
        required: true

  User:
    type: object
    properties:
      id:
        type: integer
        required: true
      username:
        type: string
        required: true
      firstname:
        type: string
        required: true
      lastname:
        type: string
        required: true
      password:
        type: string
        required: true
      role:
        type: Role
        required: true

  Category:
    type: object
    properties:
      id:
        type: integer
        required: true
      name:
        type: string
        required: true

  NewCategory:
    type: object
    properties:
      name:
        type: string
        required: true

  Product:
    type: object
    properties:
      id:
        type: integer
        required: true
      name:
        type: string
        required: true
      price:
        type: number
        required: true
      details:
        type: string
        required: true
      category:
        type: Category
        required: true

  NewProduct:
    type: object
    properties:
      name:
        type: string
        required: true
      price:
        type: number
        required: true
      details:
        type: string
        required: true
      category:
        type: string
        required: true

  NewUser:
    type: object
    properties:
     username:
       type: string
       required: true
     firstname:
       type: string
       required: true
     lastname:
       type: string
       required: true
     password:
       type: string
       required: true
     roletype:
       type: string
       required: true
