version: "3.7"

services:
  userdb:
    image: mysql:5.7
    volumes:
      - "./userdb_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: usercore
      MYSQL_PASSWORD: usercore
    expose:
      - "3306"
    networks:
      - ps-network

  userservice:
    build:
      context: .
      labels:
        - userservice
    ports:
      - "8888:8080"
    networks:
      - ps-network
    depends_on:
      - userdb

volumes:
  userdb_data:

networks:
  ps-network:
    driver: bridge
